language: python
before_install:
  - apt-get update
  - apt-get install curl software-properties-common -y
  - add-apt-repository ppa:jonathonf/rustlang -y
  - apt-get install rustc -y
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - pytest -s
