language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install curl software-properties-common -y
  - sudo add-apt-repository ppa:jonathonf/rustlang -y
  - sudo apt-get install rustc cargo -y
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - pytest -s
